# Generated by Django 4.1.2 on 2022-10-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="auctionListings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=300)),
                ("price", models.IntegerField()),
                ("photo", models.URLField(max_length=300)),
                ("dateCreated", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
