# Generated by Django 4.1.2 on 2022-10-29 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlistings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dateCreated",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="auctionlistings",
            name="dateCreated",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
