# Generated by Django 4.1.2 on 2022-10-30 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_remove_user_datecreated"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="photo",
            field=models.URLField(max_length=500),
        ),
    ]
