# Generated by Django 4.1.2 on 2022-10-30 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_auctionlisting_author_auctionlisting_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
