# Generated by Django 4.1.2 on 2022-10-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_category_alter_auctionlisting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="description",
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
