# Generated by Django 4.1.2 on 2022-10-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_auctionlisting_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="description",
            field=models.CharField(max_length=1100),
        ),
    ]
