# Generated by Django 4.1.2 on 2022-10-30 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_alter_auctionlisting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="description",
            field=models.CharField(max_length=600),
        ),
    ]
