# Generated by Django 4.1.2 on 2022-10-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_alter_auctionlisting_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="price",
            field=models.FloatField(),
        ),
    ]
