# Generated by Django 4.1.2 on 2022-11-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_alter_auctionlisting_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="isWatchList",
            field=models.BooleanField(default=False),
        ),
    ]
