# Generated by Django 4.1.2 on 2022-11-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_comments"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
